# 02 - Pandas - Series

In [2]:
import numpy as np
import pandas as pd
import os
import sys
from IPython.display import display

print("="*15+" PANDAS VERSIÓN")
print(pd.__version__) # imprime versión de pandas (sólo números)

=============== PANDAS VERSIÓN
2.3.3

# SERIES
pd.Series()
## Series no tiene Display
serie1_prueba = pd.Series(np.array(["Pepe","Paco","Manolo","Ana"]), name="Gente")
# Sintaxis para DataFrame
df1_prueba = pd.DataFrame({"nombre": serie1_prueba, "numero": serie2_prueba})

In [ ]:
serie1_prueba = pd.Series(np.array(["Pepe","Paco","Manolo","Ana"]), name="Gente")
serie1_prueba 
print(serie1_prueba) # Le pone índice y dtype: object
serie2_prueba = pd.Series(np.random.rand(4))
print(serie2_prueba)
# SINTAXIS DATAFRAME pd.DataFrame ({ "nombre": array})
df1_prueba = pd.DataFrame({"nombre": serie1_prueba, "numero": serie2_prueba})
display(df1_prueba)
df1_prueba.insert( 2, "Nueva columna", np.random.uniform(10,20,4)) # último numero es cuantos genera
df1_prueba.insert( 3, "Otra columna", [10,20,pd.NA,40])
display(df1_prueba)

0      Pepe
1      Paco
2    Manolo
3       Ana
Name: Gente, dtype: object
0    0.741131
1    0.754541
2    0.053747
3    0.768991
dtype: float64

   nombre    numero
0    Pepe  0.741131
1    Paco  0.754541
2  Manolo  0.053747
3     Ana  0.768991

   nombre    numero  Nueva columna Otra columna
0    Pepe  0.741131      16.086884           10
1    Paco  0.754541      19.413428           20
2  Manolo  0.053747      17.511890         <NA>
3     Ana  0.768991      12.651015           40

# DataFrame