In [1]:
import numpy as np
import pandas as pd
import os
from IPython.display import display

os.system('cls')

# 1. LECTURAS
print("= 1. LECTURAS ==")
# 1.1 El Excel
# Hay que instalar pip install openpyxl
print("== 1.1 LECTURA DEL EXCEL ==")

# 1.1.1 VENTAS
print("=== 1.1.1 Head e Info de la hoja VENTAS")
df_excel_ventas = pd.read_excel("ventas_ud1.xlsx", sheet_name="Ventas")
display(df_excel_ventas.head())
display(df_excel_ventas.info())

# 1.1.2 CLIENTES
print("=== 1.1.2 Head de la hoja CLIENTES")
df_excel_clientes = pd.read_excel("ventas_ud1.xlsx", sheet_name="Clientes")
display(df_excel_clientes.head())

# 1.1.3 PARAMETROS
print("=== 1.1.3 Head de la hoja PARAMETROS")
df_excel_parametros = pd.read_excel("ventas_ud1.xlsx", sheet_name="Parametros")
display(df_excel_parametros.head())

# 1.2 El CSV
print("== 1.2 LECTURA DEL CSV ==")
print("=== 1.2.1 Head e Info de la hoja VENTAS")
ventas_csv_df = pd.read_csv("ventas_ud1.csv",sep=";")
display(ventas_csv_df.head())
display(ventas_csv_df.info())

# COMPROBACIONES
print("\n= 2. COMPROBACIONES ==")

# 2.1 IDs únicos en Ventas: comprobar que id no tiene duplicados.
print("\n==== 2.1 IDs únicos en Ventas: comprobar que id no tiene duplicados.")
#assert df_excel_ventas["Id"].is_unique, "Los ids no son únicos"
if (df_excel_ventas["Id"].is_unique):
    print(f"{df_excel_ventas["Id"].is_unique}: No hay Id repetidos")
else:
    print(f"{df_excel_ventas["Id"].is_unique}: Hay Id repetidos")



# 2.2 Valores nulos: contar cuántos nulos hay por columna en Ventas.
print("\n==== 2.2 Valores nulos: contar cuántos nulos hay por columna en Ventas.")
'''
INTENTO PRIMERO NO MUY ELEGANTE
print(f"Valores nulos en la columna Id: {df_excel_ventas['Id'].isnull().sum()}")
print(f"Valores nulos en la columna Producto: {df_excel_ventas['Producto'].isnull().sum()}")
print(f"Valores nulos en la columna Precio: {df_excel_ventas['Precio'].isnull().sum()}")
print(f"Valores nulos en la columna Unidades: {df_excel_ventas['Unidades'].isnull().sum()}")
print(f"Valores nulos en la columna Descuento: {df_excel_ventas['Descuento'].isnull().sum()}")
print(f"Valores nulos en la columna Pagado: {df_excel_ventas['Pagado'].isnull().sum()}")
print(f"Valores nulos en la columna Observaciones: {df_excel_ventas['Observaciones'].isnull().sum()}")
'''

columnas_ventas = df_excel_ventas.columns # Para conseguir un iterable con los nomobres de las columnas
for columna_ventas in columnas_ventas: # Ahora ya no hay que ponerlos uno a uno
    print(f"Valores nulos en la columna {columna_ventas}: {df_excel_ventas[columna_ventas].isnull().sum()}")

# 2.3 Fechas: convertir fecha a tipo fecha (si no se detecta bien) y comprobar el tipo final.
print("\n==== 2.3 Fechas: convertir fecha a tipo fecha (si no se detecta bien) y comprobar el tipo final.")
print("Solo hay fechas en la hoja 'Clientes', columna 'Fecha_alta'")
print(df_excel_clientes["Fecha_alta"].dtype)
print("Son fechas tipo 'datetime64[ns]'; no hay que realizar ninguna conversión.")
display(df_excel_clientes["Fecha_alta"].info)


# 2.4 Sí/No a booleano: transformar pagado (“Sí”/“No”) a True/False en una columna nueva pagado_bool.
print("\n==== 2.4 Sí/No a booleano: transformar pagado (“Sí”/“No”) a True/False en una columna nueva pagado_bool.")
df_excel_ventas["pagado_bool"] = df_excel_ventas["Pagado"].map({"Si" : True, "No" : False})
display(df_excel_ventas)


# 2.5 Cálculo: crear una columna importe = precio * unidades.
print("\n==== 2.5 Cálculo: crear una columna importe = precio * unidades.")
df_excel_ventas["importe"] = df_excel_ventas["Precio"] * df_excel_ventas["Unidades"]
display(df_excel_ventas)

# 2.6 Si descuento existe, crear importe_final aplicando descuento cuando haya valor
# (y dejando el cálculo correcto cuando esté vacío).
print("\n==== 2.6 Si descuento existe, crear importe_final aplicando descuento cuando haya valor\n(y dejando el cálculo correcto cuando esté vacío).")
#print(df_excel_ventas["Descuento"].isnull())

''' ESTO NO FUNCIONA !!!
if (df_excel_ventas["Descuento"].isnull().loc() == True):
    df_excel_ventas["importe_final"] = " Sin descuento"
else:
    df_excel_ventas["importe_final"] = "CON descuento"
'''
#df_excel_ventas["importe_final"] = df_excel_ventas["Descuento"].isnull()
'''
df_excel_ventas["importe_final"] = "CON descuento"
df_excel_ventas.loc[
    df_excel_ventas["Descuento"].isnull(),
    "importe_final"
] = "Sin descuento"
'''
df_excel_ventas["importe_final"] = df_excel_ventas["Unidades"] * (df_excel_ventas["Precio"] - (df_excel_ventas["Precio"] * (df_excel_ventas["Descuento"]/100 )))
df_excel_ventas.loc[
    df_excel_ventas["Descuento"].isnull(),
    "importe_final"
    ] = df_excel_ventas["Unidades"] * df_excel_ventas["Precio"]

display(df_excel_ventas)

''' Prueba para mostrar un importe final unitario con descuento y luego un importe final multiplicado por unidades
df_excel_ventas["importe_final_unitario"] = df_excel_ventas["Precio"] - (df_excel_ventas["Precio"] * (df_excel_ventas["Descuento"]/100 ))
df_excel_ventas.loc[
    df_excel_ventas["Descuento"].isnull(),
    "importe_final_unitario"
    ] = df_excel_ventas["Precio"]
df_excel_ventas["importe_final"] = df_excel_ventas["Precio"] * df_excel_ventas["Unidades"]

		IMPORTE DESCONTADO UNIDAD	IMPORTE FINAL 
1	Naranjas	10,048500		2,009,70 
2	Manzanas	14,662500		4.472,0625
3	Peras		11,128860		1.647,07128
4	Plátanos	29,700000		25720.20000
5	Uva		20,090000		4721.15000
6	Mandarinas	12,000000		4956,00--- NaN - SIN DESCUENTO
7	Limones		9,201500		2990.48750
8	Kiwis		13,000000		11063,00--- NaN - SIN DESCUENTO
9	Piña		19,590200		3056.07120
10	Melocotón	17,820000		6557.76000
11	Ciruelas	17,890000		11574,83--- NaN - SIN DESCUENTO
12	Cerezas		23,396855		14599.63752

display(df_excel_ventas)

'''

= 1. LECTURAS ==
== 1.1 LECTURA DEL EXCEL ==
=== 1.1.1 Head e Info de la hoja VENTAS

   Id  Producto  Precio  Unidades  Descuento Pagado Observaciones
0   1  Naranjas   10.15       200       1.00     Si    Muy buenas
1   2  Manzanas   15.00       305       2.25     No     Si gusano
2   3     Peras   11.14       148       0.10     Si           NaN
3   4  Plátanos   30.00       866       1.00     No   De Canarias
4   5       Uva   20.50       235       2.00     Si    Nochevieja

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             12 non-null     int64
 1   Producto       12 non-null     object
 2   Precio         12 non-null     float64
 3   Unidades       12 non-null     int64
 4   Descuento      9 non-null      float64
 5   Pagado         12 non-null     object
 6   Observaciones  8 non-null      object
dtypes: float64(2), int64(2), object(3)
memory usage: 804.0+ bytes

None

=== 1.1.2 Head de la hoja CLIENTES

   Id_cliente           Nombre Fecha_alta Activo                  Email
0           1       Pepe Pérez 2001-01-01     Si    pepeperez@gmail.com
1           2  Manolo Martínez 2010-02-12     No                    NaN
2           3       Ana Angulo 2005-03-15     Si  anaangulo@hotmail.com
3           4       Luis López 2018-06-14     No     luislopez@yahoo.es
4           5    Gracia García 2008-05-20     Si                    NaN

=== 1.1.3 Head de la hoja PARAMETROS

              Clave                Valor
0               IVA                 0.21
1            Moneda                    €
2            Centro     IES Severo Ochoa
3  Fecha_generación  2000-01-02 00:00:00

== 1.2 LECTURA DEL CSV ==
=== 1.2.1 Head e Info de la hoja VENTAS

   Id  Producto Precio  Unidades Descuento Pagado Observaciones
0   1  Naranjas  10,15       200         1     Si    Muy buenas
1   2  Manzanas     15       305      2,25     No     Si gusano
2   3     Peras  11,14       148       0,1     Si           NaN
3   4  Plátanos     30       866         1     No   De Canarias
4   5       Uva   20,5       235         2     Si    Nochevieja

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             12 non-null     int64
 1   Producto       12 non-null     object
 2   Precio         12 non-null     object
 3   Unidades       12 non-null     int64
 4   Descuento      9 non-null      object
 5   Pagado         12 non-null     object
 6   Observaciones  8 non-null      object
dtypes: int64(2), object(5)
memory usage: 804.0+ bytes

None

= 2. COMPROBACIONES ==

==== 2.1 IDs únicos en Ventas: comprobar que id no tiene duplicados.
True: No hay Id repetidos

==== 2.2 Valores nulos: contar cuántos nulos hay por columna en Ventas.
Valores nulos en la columna Id: 0
Valores nulos en la columna Producto: 0
Valores nulos en la columna Precio: 0
Valores nulos en la columna Unidades: 0
Valores nulos en la columna Descuento: 3
Valores nulos en la columna Pagado: 0
Valores nulos en la columna Observaciones: 4

==== 2.3 Fechas: convertir fecha a tipo fecha (si no se detecta bien) y comprobar el tipo final.
Solo hay fechas en la hoja 'Clientes', columna 'Fecha_alta'
datetime64[ns]
Son fechas tipo 'datetime64[ns]'; no hay que realizar ninguna conversión.

<bound method Series.info of 0   2001-01-01
1   2010-02-12
2   2005-03-15
3   2018-06-14
4   2008-05-20
5   2020-03-30
6   2021-08-07
7   2012-12-21
Name: Fecha_alta, dtype: datetime64[ns]>

==== 2.4 Sí/No a booleano: transformar pagado (“Sí”/“No”) a True/False en una columna nueva pagado_bool.

,Id,Producto,Precio,Unidades,Descuento,Pagado,Observaciones,pagado_bool
0,1,Naranjas,10.15,200,1.00,Si,Muy buenas,True
1,2,Manzanas,15.00,305,2.25,No,Si gusano,False
2,3,Peras,11.14,148,0.10,Si,NaN,True
3,4,Plátanos,30.00,866,1.00,No,De Canarias,False
4,5,Uva,20.50,235,2.00,Si,Nochevieja,True
5,6,Mandarinas,12.00,413,NaN,No,NaN,False
6,7,Limones,9.56,325,3.75,Si,Para zumos,True
7,8,Kiwis,13.00,851,NaN,No,De Nueva Zelanda,False
8,9,Piña,19.99,156,2.00,Si,Colada,True
9,10,Melocotón,18.00,368,1.00,No,NaN,False
10,11,Ciruelas,17.89,647,NaN,Si,No pasas,True
11,12,Cerezas,25.01,624,6.45,No,NaN,False

==== 2.5 Cálculo: crear una columna importe = precio * unidades.

,Id,Producto,Precio,Unidades,Descuento,Pagado,Observaciones,pagado_bool,importe
0,1,Naranjas,10.15,200,1.00,Si,Muy buenas,True,2030.00
1,2,Manzanas,15.00,305,2.25,No,Si gusano,False,4575.00
2,3,Peras,11.14,148,0.10,Si,NaN,True,1648.72
3,4,Plátanos,30.00,866,1.00,No,De Canarias,False,25980.00
4,5,Uva,20.50,235,2.00,Si,Nochevieja,True,4817.50
5,6,Mandarinas,12.00,413,NaN,No,NaN,False,4956.00
6,7,Limones,9.56,325,3.75,Si,Para zumos,True,3107.00
7,8,Kiwis,13.00,851,NaN,No,De Nueva Zelanda,False,11063.00
8,9,Piña,19.99,156,2.00,Si,Colada,True,3118.44
9,10,Melocotón,18.00,368,1.00,No,NaN,False,6624.00
10,11,Ciruelas,17.89,647,NaN,Si,No pasas,True,11574.83
11,12,Cerezas,25.01,624,6.45,No,NaN,False,15606.24

==== 2.6 Si descuento existe, crear importe_final aplicando descuento cuando haya valor
(y dejando el cálculo correcto cuando esté vacío).

,Id,Producto,Precio,Unidades,Descuento,Pagado,Observaciones,pagado_bool,importe,importe_final
0,1,Naranjas,10.15,200,1.00,Si,Muy buenas,True,2030.00,2009.70000
1,2,Manzanas,15.00,305,2.25,No,Si gusano,False,4575.00,4472.06250
2,3,Peras,11.14,148,0.10,Si,NaN,True,1648.72,1647.07128
3,4,Plátanos,30.00,866,1.00,No,De Canarias,False,25980.00,25720.20000
4,5,Uva,20.50,235,2.00,Si,Nochevieja,True,4817.50,4721.15000
5,6,Mandarinas,12.00,413,NaN,No,NaN,False,4956.00,4956.00000
6,7,Limones,9.56,325,3.75,Si,Para zumos,True,3107.00,2990.48750
7,8,Kiwis,13.00,851,NaN,No,De Nueva Zelanda,False,11063.00,11063.00000
8,9,Piña,19.99,156,2.00,Si,Colada,True,3118.44,3056.07120
9,10,Melocotón,18.00,368,1.00,No,NaN,False,6624.00,6557.76000
10,11,Ciruelas,17.89,647,NaN,Si,No pasas,True,11574.83,11574.83000
11,12,Cerezas,25.01,624,6.45,No,NaN,False,15606.24,14599.63752

' Prueba para mostrar un importe final unitario con descuento y luego un importe final multiplicado por unidades\ndf_excel_ventas["importe_final_unitario"] = df_excel_ventas["Precio"] - (df_excel_ventas["Precio"] * (df_excel_ventas["Descuento"]/100 ))\ndf_excel_ventas.loc[\n    df_excel_ventas["Descuento"].isnull(),\n    "importe_final_unitario"\n    ] = df_excel_ventas["Precio"]\ndf_excel_ventas["importe_final"] = df_excel_ventas["Precio"] * df_excel_ventas["Unidades"]\n\n\t\tIMPORTE DESCONTADO UNIDAD\tIMPORTE FINAL \n1\tNaranjas\t10,048500\t\t2,009,70 \n2\tManzanas\t14,662500\t\t4.472,0625\n3\tPeras\t\t11,128860\t\t1.647,07128\n4\tPlátanos\t29,700000\t\t25720.20000\n5\tUva\t\t20,090000\t\t4721.15000\n6\tMandarinas\t12,000000\t\t4956,00--- NaN - SIN DESCUENTO\n7\tLimones\t\t9,201500\t\t2990.48750\n8\tKiwis\t\t13,000000\t\t11063,00--- NaN - SIN DESCUENTO\n9\tPiña\t\t19,590200\t\t3056.07120\n10\tMelocotón\t17,820000\t\t6557.76000\n11\tCiruelas\t17,890000\t\t11574,83--- NaN - SIN DESCUENTO\n12\tCerezas\t\t23,396855\t\t14599.63752\n\ndisplay(df_excel_ventas)\n\n'